version: "3.7"

services:
  app:
    image: fshangala/pc-automation-server:main
    ports:
      - 80:80
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pcautomations
    volumes:
      - lambo:/var/lib/mysql
  redis:
    image: redis

volumes:
  lambo:
