version: "3.7"

services:
  app:
    build: .
    volumes:
      - lambo: lambo:/usr/local/lib/python3.10/site-packages/
    ports:
      - 8000:8000
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pcautomation
  redis:
    image: redis

volumes:
  lambo:
        