# Generated by Django 4.0.5 on 2022-10-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='sfname',
            new_name='repositoryname',
        ),
        migrations.RemoveField(
            model_name='software',
            name='sffile',
        ),
        migrations.AddField(
            model_name='software',
            name='repositoryowner',
            field=models.CharField(default='fshangala', max_length=200),
        ),
    ]
