# Generated by Django 4.0.5 on 2023-02-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0003_betsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='betsite',
            name='alt_stake_input',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
