# Generated by Django 4.0.5 on 2023-03-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0005_betsitedesktop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='repositoryname',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
