# Generated by Django 4.0.5 on 2023-02-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0006_alter_software_repositoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='betsitedesktop',
            name='login_button',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='betsitedesktop',
            name='username_input',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
