version: "3.7"

services:
  app:
    build: .
    ports:
      - 8000:8000
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pcautomation
  redis:
    image: redis
        