version: "3.7"

services:
  app:
    build: .
    command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pcautomation
        