# Generated by Django 4.0.5 on 2022-11-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcautomation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
