# Generated by Django 4.0.5 on 2022-12-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcautomation', '0002_connection_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connection',
            new_name='LamboConnection',
        ),
    ]
