# Generated by Django 4.0.5 on 2022-12-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcautomation', '0003_rename_connection_lamboconnection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LamboConnection',
            new_name='Connection',
        ),
    ]
