# Generated by Django 4.0.5 on 2023-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcautomation', '0004_rename_lamboconnection_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loggedin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicetype', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('url', models.URLField(null=True)),
                ('datetime', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
