# Generated by Django 4.0.5 on 2023-08-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcautomation', '0006_connection_l_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
